### ISSUE TITLE
Название репозитория

### ISSUE THREAD

**Issue by BunnyNoBugs** [pseusys/ClassicDungeon#1]
Не должен ли репозиторий называться кебаб-кейсом: `classic-dungeon`?

**Comment by pseusys** [comment]
Я так понимаю, что не обязательно. Взгляни на [ребят из Google](https://github.com/firebase/), они называют по-разному. Мне кажется это можно связать с кейсом основного языка проекта. В данном случае - kotlin с `camelCase`. Но если тебе не нравится, можем переименовать, это не существенно.

**Comment by BunnyNoBugs** [comment]
Okay, agreed on `ClassicDungeon`
